services:
  frontend:
    networks:
      - traefik-public
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-public
      traefik.http.routers.frontend.rule: Host(`${SITE_HOST}`)
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: "8080"

networks:
  traefik-public:
    external: true
