services:
  frontend:
    networks:
      - traefik-public
      - default
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik-public"
      traefik.http.routers.${APP_NAME}-frontend.rule: "Host(`${SITE_HOST}`)"
      traefik.http.routers.${APP_NAME}-frontend.entrypoints: "web"
      traefik.http.services.${APP_NAME}-frontend.loadbalancer.server.port: "8080"

networks:
  traefik-public:
    external: true
